### ISSUE TITLE
NullPointer exception when resize factor != X1

### ISSUE THREAD

**Issue by botdes** [DataSketches/sketches-core#121]
Hi, I'm running data sketches on spark using scala serialisation wrapper like this.

```
@throws(classOf[IOException])
  private def writeObject(out: ObjectOutputStream): Unit = synchronized {
    out.writeObject(union.toByteArray)
  }

  @throws(classOf[IOException])
  private def readObject(in: ObjectInputStream): Unit = synchronized {
    val bytes = in.readObject().asInstanceOf[Array[Byte]]
    Sketches.wrapUnion(new NativeMemory(bytes))
  }
```

But when my sketches don't have `ResizeFactor.X1` property set I get a null pointer error:
```
Caused by: java.lang.NullPointerException
  at com.yahoo.sketches.theta.DirectQuickSelectSketch.hashUpdate(DirectQuickSelectSketch.java:404)
  at com.yahoo.sketches.theta.UpdateSketch.update(UpdateSketch.java:169)
  at com.yahoo.sketches.theta.UnionImpl.update(UnionImpl.java:269)
  at com.myproject.spark.SerUnion.update(SerUnion.scala:32)
  at $anonfun$createDataSketches$2.apply(<console>:73)
  at $anonfun$createDataSketches$2.apply(<console>:73)
  at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:190)
  at org.apache.spark.util.collection.ExternalSorter$$anonfun$5.apply(ExternalSorter.scala:189)
  at org.apache.spark.util.collection.AppendOnlyMap.changeValue(AppendOnlyMap.scala:144)
  at org.apache.spark.util.collection.SizeTrackingAppendOnlyMap.changeValue(SizeTrackingAppendOnlyMap.scala:32)
  at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:195)
  at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:63)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
  at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
  at org.apache.spark.scheduler.Task.run(Task.scala:86)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
```

I'm using version 0.8.3 for the following modules.
```
 'com.yahoo.datasketches:sketches:0.8.3'
 'com.yahoo.datasketches:memory:0.8.3'
 'com.yahoo.datasketches:sketches-core:0.8.3'
```

**Comment by AlexanderSaydakov** [comment]
I encountered this myself a few days ago while exploring ways of using sketches in Spark. This problem has two parts: incorrect usage and a bug in error handling. We fixed the error handling in the master branch, so it will throw an exception with a more meaningful message instead of the NullPointerException in this case.
The usage problem here is that an UpdateSketch, which can grow if ResizeFactor != X1, inside of the Union is instantiated by wrapping a NativeMemory object of a fixed size.
Solutions:
- use heapifyUnion() instead of wrapUnion(). This will be slower, but it will create a copy on the heap, which can grow as needed.
- if you really want to manage the memory yourself, implement and set a MemoryRequest for the NativeMemory object so that it could grow.
- use ResizeFactor.X1, which preallocates the UpdateSketch of the maximum size upfront, so it doesn't need to grow.

However, the real usage problem here, in my view, is the necessity to serialize and deserialize Unions or UpdateSketches in the first place. The right way would be to arrange a two-phase process (similar to map-reduce), so that in the first phase the input is divided into chunks, each chunk is processed on a particular executor in such a way that a single UpdateSketch is created and updated with all the input items and then serialized only once to ship the result to a second phase executor. In the second phase we only merge the sketches prepared in the first phase, so the sketches can be serialized as CompactSketches at the end of the first phase.
We successfully do this in Hive using the UDAF (user-defined aggregate function) interface. I explored ways of doing this in Spark lately. The best I could manage so far was aggregate() method on RDD like this (I am using Java):

public class Aggregate {

  public static void main(String[] args) {
    SparkConf conf = new SparkConf();
    JavaSparkContext context = new JavaSparkContext(conf);
    JavaRDD<String> lines = context.textFile("words.txt");
    SketchWrapper initialValue = new SketchWrapper();
    SketchWrapper sketch = lines.aggregate(initialValue, new Add(), new Combine());
    System.out.println("Unique count: " + String.format("%,f", sketch.getEstimate()));
  }

  static class Add implements Function2<SketchWrapper, String, SketchWrapper> {
    public SketchWrapper call(final SketchWrapper sketch, final String value) throws Exception {
      sketch.update(value);
      return sketch;
    }
  }

  static class Combine implements Function2<SketchWrapper, SketchWrapper, SketchWrapper> {
    static final SketchWrapper emptySketchWrapped = new SketchWrapper(UpdateSketch.builder().build().compact());

    public SketchWrapper call(final SketchWrapper sketchWrapper1, final SketchWrapper sketchWrapper2) throws Exception {
      if (sketchWrapper1.getSketch() == null && sketchWrapper2.getSketch() == null) return emptySketchWrapped;
      if (sketchWrapper1.getSketch() == null) return sketchWrapper2;
      if (sketchWrapper2.getSketch() == null) return sketchWrapper1;
      CompactSketch sketch1 = sketchWrapper1.getCompactSketch();
      CompactSketch sketch2 = sketchWrapper2.getCompactSketch();
      return new SketchWrapper(PairwiseSetOperations.union(sketch1, sketch2));
    }
  }

}

public class SketchWrapper implements Serializable {

  private Sketch sketch;

  public SketchWrapper() {
  }

  public SketchWrapper(final Sketch sketch) {
    this.sketch = sketch;
  }

  public Sketch getSketch() {
    return sketch;
  }

  public CompactSketch getCompactSketch() {
    if (sketch == null) return null;
    if (sketch instanceof UpdateSketch) return ((UpdateSketch) sketch).compact();
    return (CompactSketch) sketch;
  }

  public void update(final String value) {
    if (sketch == null) sketch = UpdateSketch.builder().build();
    if (sketch instanceof UpdateSketch) {
      ((UpdateSketch) sketch).update(value);
    } else {
      throw new RuntimeException("update() in a wrong phase");
    }
  }

  public double getEstimate() {
    if (sketch == null) return 0.0;
    if (sketch instanceof UpdateSketch) throw new RuntimeException("getEstimate() in a wrong phase");
    return  sketch.getEstimate();
  }

  private void writeObject(final ObjectOutputStream out) throws IOException {
    if (sketch == null) {
      out.writeInt(0);
      return;
    }
    final byte[] serializedSketchBytes = ((UpdateSketch) sketch).compact().toByteArray();
    out.writeInt(serializedSketchBytes.length);
    out.write(serializedSketchBytes);
  }

  private void readObject(final ObjectInputStream in) throws IOException, ClassNotFoundException {
    final int length = in.readInt();
    if (length == 0) return;
    final byte[] serializedSketchBytes = new byte[length];
    in.readFully(serializedSketchBytes);
    sketch = Sketches.wrapSketch(new NativeMemory(serializedSketchBytes));
  }

}

This works fine for me, but testing on a large data set shows that our Hive UDAF seems to be faster: ~1.5 min in Hive, ~2.5 min in Spark for the same input. There are many problems with such comparisons though. It is hard to make sure we compare the same thing. The cluster has a variable load, Spark and Hive can use different degree of parallelism and so on. I didn't have much time yet to analyze all the details. And I am still exploring other ways.

**Comment by botdes** [comment]
Hi Alexander, 
Thank you very much for the quick response.
I think `heapifyUnion()` is exactly what I need.
I use the similar approach with aggregateByKey function but instead of `PairwiseSetOperations.union(sketch1, sketch2)` I just update the `sketch1` sketch using `update` method, it works a bit faster to me.

**Comment by AlexanderSaydakov** [comment]
> I use the similar approach with aggregateByKey function

I am not sure the approach is similar. The key in my example is that no updates happen after serialize-deserialize. In other words, the serialize-deserialize cycles happen between the update phase and merge phase only. The exception you were getting is an indication that in your case updates happen after serialize-deserialize. If this happens too often - between each update would be the worst case - it can destroy all the advantages of using such a library as opposed to a brute-force computation.

Could you share your code? Did you do any performance comparisons yet?

**Comment by botdes** [comment]
My task is to calculate a number of data sketches, one per each key, I have a number of tuples (attribute, value) and I want to calculate a datasketch for each attribute. In the end I get ~100 000 datasketches.

I see that exception in the stack trace I posted refers to `update` method, but the current code was failing in merge method.

My code is the following:
```
class SerUnion(var union: Option[Union] = None) extends Serializable {
  def createUnion(): Union = new SetOperationBuilder().buildUnion()

  @throws(classOf[IOException])
  private def writeObject(out: ObjectOutputStream): Unit = {
    union match {
      case None => out.writeInt(0)
      case Some(s) =>
        val serializedSketchBytes = s.toByteArray
        out.writeInt(serializedSketchBytes.length)
        out.write(serializedSketchBytes)
    }
  }

  @throws(classOf[IOException])
  private def readObject(in: ObjectInputStream): Unit = {
    val length = in.readInt()
    if (length == 0) {
      union = None
    } else {
      val serializedSketchBytes = new Array[Byte](length)
      in.readFully(serializedSketchBytes)
      union = Some(SetOperation.heapify(new NativeMemory(serializedSketchBytes)).asInstanceOf[Union])
    }
  }

  def update(datum: String): SerUnion = {
    if (union.isEmpty) {
      union = Some(createUnion())
    }
    union.foreach(_.update(datum))
    this
  }

  def merge(otherUnion: SerUnion): SerUnion = {
    if (union.isEmpty) {
      union = otherUnion.union
    } else if (otherUnion.union.isEmpty) {
      //do nothing
    } else {
      union.get.update(otherUnion.union.get.getResult())
    }
    this
  }

  def toByteArray: Array[Byte] = {
    union.map(_.toByteArray).getOrElse(Array())
  }
}
```
And aggregate operation looks like this.
```
  def createDataSketches(input: RDD[(String, String)]): RDD[(String, SerUnion)] = {
    input.aggregateByKey(new SerUnion())(
      seqOp = {case (union, data) => union.update(data)},
      combOp = {case (union1, union2) => union1.merge(union2)}
    ) }
  }
```

I will post results of comparison a bit later.

**Comment by AlexanderSaydakov** [comment]
Thanks for sharing your code. I am going to try something like this myself.

The reason I proposed to have a serializable wrapper around a sketch, not a union, is that I wanted to find an optimal way, which avoids serializing and deserializing until a sketch is updated with all the input and is transferred to another executor for merging with other sketches. In my code, as you can see, I converted sketches to the compact form in writeObject(), so that it would be impossible to update them on the other end. This is more efficient and also serves as a proof that no updates happen after a serialize-deserialize cycle. We don't really want to serialize and deserialize unions.

So far I only tried aggregate() producing one global sketch. I also wanted to try aggregateByKey() to build multiple sketches, but I didn't reach that point yet.

**Comment by AlexanderSaydakov** [comment]
> I see that exception in the stack trace I posted refers to update method, but the current code was failing in merge method.

Could you clarify if this code you posted is working or you are still getting some exception?

**Comment by botdes** [comment]
Since I've changed from `Sketch.wrap` to `SetOperation.heapify` in `readObject` method the code is working and I'm not getting exceptions anymore.

**Comment by AlexanderSaydakov** [comment]
> Since I've changed from Sketch.wrap to SetOperation.heapify in readObject method the code is working and I'm not getting exceptions anymore.

I see. Wrapping a sketch or a union is much faster than heapifying, but you cannot (easily) grow the wrapped object, which you are doing by using one of them as the target union. You might want to try instantiating a fresh union to use as a target, and only call getResult() on the incoming objects. This way wrap can be used, but notice that in such a case unions are serialized and deserialized just to call getResult() on them on the other end. The output of getResult() is a CompactSketch. This is why I strongly suggest having a wrapper around a Sketch, not a Union, and also calling compact() in writeObject. In general, serializing Unions (or UpdateSketches) should be done only if really needed for some specific purpose, which is not the case here.

**Comment by leerho** [comment]
@botdes 

I think there are two concepts that are explained [here](https://datasketches.github.io/api/core/snapshot/apidocs/com/yahoo/sketches/theta/Sketch.html#heapify-com.yahoo.memory.Memory-) and [here](https://datasketches.github.io/api/core/snapshot/apidocs/com/yahoo/sketches/theta/Sketch.html#wrap-com.yahoo.memory.Memory-) that perhaps you missed so I will try do a better job here :)

A Memory object is essentially a blob of bytes that can be backed by either a byte[], a ByteBuffer (which are on-heap), or a block of native, off-heap memory.  

A **heapify** operation takes a Memory object and constructs an on-heap sketch, which does not retain any reference to the original Memory object.  You can think of this a deserialize operation with the additional subtlety that the original blob of bytes could be backed by some on-heap object or backed by true off-heap memory.  The newly created on-heap sketch doesn't know or care. 

A **wrap** operation takes a Memory object and constructs a thin, on-heap sketch object that _wraps_ the blob of bytes as if it were its only memory and treats it as its own data structure.   Currently only the Theta and (soon) the Quantile sketches allow this wrapping capability. 

On really large systems with large RAM (e.g., a Terabyte) most of that RAM is dedicated to data, and is too large to be practically managed by a single JVM.   Now suppose that much of that data consists of billions (yes, billions) of sketch images.  If you want to be merging across millions of these sketches in a single query operation, you really don't want to be deserializing each sketch onto the heap before merging into a union object.  That would be horribly slow!
This is where the wrap operation comes into play.  The wrapping sketch only has a pointer to the Memory blob (and sometimes a few other metadata items), thus eliminating the need for deserialization.   This allows extremely fast merging operations (we have observed ~15 million sketches per second in production and I have measured (in ideal test environments) up to 60 million sketch merges per second.  

Now, if you wrap a sketch and intend to **update** that sketch you must do one of two things:
* The memory capacity allocated to the Memory object must be large enough to allow the required growth, or
*  You provide a MemoryRequest object to the sketch when you do the wrap operation. This MR object is a callback to the caller of the wrap method to provide a larger memory space, if required.

When you do a _toByteArray()_ the size of the returned byte array is exactly the number of bytes required to hold the current sketch and no more.

Heapifying this byte array in another stage allows the sketch to grow on the heap as a normal java object.  Wrapping this byte array without doing one of the above will throw an exception.

I hope this helps.

**Comment by botdes** [comment]
@leerho thanks for the explanation.
@AlexanderSaydakov thank you for your suggestion of using UpdateSketch.
I've changed my code to use UpdateSketch for creating sketches and Union for merging sketches but on reduce phase `PairwiseSetOperations.union` looks to be a bit slow, I guess because it requires a creation of a new Sketch. 
I think it's better to do union operation which changes existing Union object and `aggregateByKey` can help with it because it doesn't serialise object during reduce operation, so it's allows to use the same Union object during whole reduce phase.
The only question I have in this situation is how to convert from UpdateSketch to Union. I use code like this, but I want to make sure that the code is correct.

```
  var storedSketch: Option[Either[Sketch, Union]] = None 

  @throws(classOf[IOException])
  private def writeObject(out: ObjectOutputStream): Unit = {
    storedSketch match {
      case None => out.writeInt(0)
      case Some(Left(sketch)) =>
        val serializedSketchBytes = sketch.asInstanceOf[UpdateSketch].compact().toByteArray
        out.writeInt(serializedSketchBytes.length)
        out.write(serializedSketchBytes)
      case Some(Right(union)) =>
        throw new RuntimeException("we shouldn't serialize unions")
    }
  }

  @throws(classOf[IOException])
  private def readObject(in: ObjectInputStream): Unit = {
    val length = in.readInt()
    if (length == 0) {
      storedSketch = None
    } else {
      val serializedSketchBytes = new Array[Byte](length)
      in.readFully(serializedSketchBytes)
      val wrapSketch = Sketches.wrapSketch(new NativeMemory(serializedSketchBytes))
      val union = createUnion()
      union.update(wrapSketch)
      storedSketch = Some(Right(union))
    }
  }
```

I compared this version with `PairwiseSetOperations` and previous one with serialised union. 
For current one and previous one got ~7m on my dataset
For `PairwiseSetOperations` got ~14m on the same dataset and cluster

**Comment by leerho** [comment]
@botdes thanks for pointing out this slowness issue.  In looking at it more closely it is definately doing more push-ups than necessary.   

Lee.

**Comment by AlexanderSaydakov** [comment]
> I think it's better to do union operation which changes existing Union object and aggregateByKey can help with it because it doesn't serialise object during reduce operation, so it's allows to use the same Union object during whole reduce phase.
The only question I have in this situation is how to convert from UpdateSketch to Union. I use code like this, but I want to make sure that the code is correct.

I am not sure I understand your point. Are you talking about the combine operation on a type T:
(T, T) => T? If so, and the type T is Union, how can you use PairwiseSetOperations.union at all? On the one hand, the result in a Sketch, so you will need to convert it to Union, which can offset the whole benefit of the PairwiseSetOperations.union. On the other hand, your intention was to keep using the same Union object for the whole merging phase.

**Comment by AlexanderSaydakov** [comment]
Just to be clear, the motivation for PairwiseSetOperations.union was to have a fast stateless union for one pair of sketches to avoid the overhead of instantiating a union, using it for just one pair, calling getResult() and discarding it.

**Comment by leerho** [comment]
@botdes 
I did some characterization runs of the speed of the PairwiseSetOps(PW) vs the classic (CL) SetOps.

The "classic" or standard setOps (Union, Intersection, AnotB) perform operations on all the different Theta Sketches (Heap, off-heap, Compact, non-Compact, Ordered, non-ordered, etc.), and enable iterative operations (except for AnotB).  

Meanwhile  the Pairwise setOps are tuned for the case where all the incoming sketches are in strictly Compact, Ordered form, which occurs frequently in large systems and is why I created this special class for that case.

All of my measurements reveal that the Pairwise operations are quite a bit faster than the classic setOps.  After I did some additional tuning, they are even faster.  The following times are in nanoseconds per union.

For example, for unions (before my latest tunings):
```
Avg PW LL time:	1346.4106     //ave Pairwise Light/Light (both sketches had only 10 entries)
Avg CL LL time:	1946.2618     //ave classic Light/Light ...
Avg LL Speedup:	1.445518774
	
Avg PW LH time:	34614.9124 //ave Pairwise Light/Heavy (sk1 had 10, sk2 had ~6K entries)
Avg CL LH time:	491183.3462
Avg LH Speedup:	14.18993469
	
Avg PW HH time:	80088.1908 //ave Pairwise Heavy/Heavy (both had ~6K entries)
Avg CL HH time:	709860.9556
Avg HH Speedup:	8.863490966

After some additional tuning of the code:
Avg PW LL time:	1012.7687
Avg CL LL time:	1599.8566
Avg LL Speedup:	1.579686063
	
Avg PW LH time:	34072.871
Avg CL LH time:	491823.9446
Avg LH Speedup:	14.43447324
	
Avg PW HH time:	77695.1158
Avg CL HH time:	714906.4467
Avg HH Speedup:	9.201433569
```

I had similar speed up results for the AnotB and Intersection operations.

So I am a bit flummoxed as to why you are getting 2X slower results using Pairwise!

I recommend that you get the latest code by cloning the current master snapshot. 

Lee.

**Comment by AlexanderSaydakov** [comment]
I summarized my examples on this page on the DataSketches web site:
https://datasketches.github.io/docs/Theta/ThetaSparkExample.html
I am still not sure these are the best approaches. They seem to do a reasonably good job.
I think we can close this issue.
