### ISSUE TITLE
Deserialize HLLSketch

### ISSUE THREAD

**Issue by hpx7** [DataSketches/sketches-core#139]
`HLLSketch` has a `toByteArray` method for serialization, but I can't figure out how to construct a `HLLSketch` from a byte array. Am I missing something?

**Comment by AlexanderSaydakov** [comment]
It seems to me that this functionality was never implemented. It must be an oversight. Added to our to-do list.

**Comment by leerho** [comment]
This has been merged into master and will be in the next release. We could use a lot more documentation on how to use these HLL sketches.
