### ISSUE TITLE
Track Purge count in ReversePurgeItemHashMap

### ISSUE THREAD

**Issue by sszuflita** [DataSketches/sketches-core#146]
I want to add a purgeCount field to the the ReversePurgeItemHashMap.
I also want to expose this in the ItemsSketch object

My use case is this: I want to be able to tell if my Stream is an enum (i.e. contains < k distinct values). This can be achieved by creating a ItemsSketch with capacity k, and then seeing if the map is ever purged.

I am happy to implement this; what do you guys think?

**Comment by leerho** [comment]
The ItemsSketch depends on the hashCode() to determine uniqueness.  Why not just extract the hashCode() of each item and feed it to a Theta UpdateSketch of size k.  If the # of unique items is < k, the answer is exact.  If greater than k, it will be approximate.  This will be much smaller, faster and much more accurate (if # > k). No need to rewrite anything.

If you also want to track the counts of number of duplicates of each item, then use a Tuple Sketch.

It is not clear why you are focusing on the FIS?

**Comment by AlexanderSaydakov** [comment]
The number of purges is an implementation detail. I don't think it should be exposed, and I don't think that you can draw any conclusions from the number. It seems that you don't really need the number, but need to know if any purges happened at all. For this you can use getMaximumError(). If it is zero, than no purges happened (given the current implementation).
On the other hand, as Lee suggested, perhaps, you just want a Theta sketch to estimate the cardinality of your stream.

**Comment by sszuflita** [comment]
I'm confused about your idea. If I feed N items into a FIS with capacity k, won't the underlying map get purged down to size k? I want to be able to determine if the map has been purged or not.

One other thought: I see that the ItemSketch provides the streamLength; it seems like if the sum of the frequency estimates equals the streamLength, then the frequent items span the stream? Or does the fact that the frequency estimates are approximate make this a bad idea?

I was focusing on the FIS out of selfishness; this could make sense elsewhere.

**Comment by sszuflita** [comment]
Ah ok, yes that is perfect! Thanks

**Comment by leerho** [comment]
So you must be using the FIS for other reasons ?

**Comment by AlexanderSaydakov** [comment]
I would argue that for cardinality estimation the right tool is Theta sketch. If your sketch size is K, and the cardinality happens to be not more than K, the sketch will be in the exact counting mode, and you can learn this fact from the sketch by calling isEstimationMode(). If this method returns false (meaning that the sketch is not in estimation mode yet) the lower and upper bounds will be equal to getEstimate()

**Comment by sszuflita** [comment]
I see. That seems like a viable alternative. It seems a bit odd that the theta sketch API supports this isEstimationMode, but that the FrequentItems doesn't have a similar boolean for IsExact (although I see how the error can be interpreted to achieve this).

You're also right; I'm using the FIS to get frequent items, and perhaps I'm overloading it a bit in order to get a cardinality estimation out of it.

I'm going to pursue the FIS maxError approach and will validate it's behavior (i.e. maxError == 0 iff no purges occur).

**Comment by AlexanderSaydakov** [comment]
> maxError == 0 iff no purges occur

That is a fact given the current algorithm. Purge means subtracting the mean value (estimated) from all the counts, keeping entries with positive counts only and increasing the max error by that amount. So purge always increases max error.

**Comment by sszuflita** [comment]
Great. I'm going to close this out.

**Comment by AlexanderSaydakov** [comment]
> I'm using the FIS to get frequent items, and perhaps I'm overloading it a bit in order to get a cardinality estimation out of it.

This is a limited cardinality estimator. If getMaxError() == 0, cardinality is exactly getNumActiveItems(), but if getMaxError() > 0, you have no idea.
