### ISSUE TITLE
JaccardSimilarity#jaccard can throw

### ISSUE THREAD

**Issue by hpx7** [DataSketches/sketches-core#153]
See https://github.com/DataSketches/sketches-core/blob/master/src/main/java/com/yahoo/sketches/theta/JaccardSimilarity.java#L46

This fails if `ceilingPowerOf2(countA + countB))` is not between the accepted range for nominal entires.

I'm happy to submit a PR with the fix + test, but didn't see any contribution guidelines.

**Comment by leerho** [comment]
Thank you for finding this.  It will be fixed in the next release, which is coming (hopefully) in the next few days.  It is fixed on master.
