### ISSUE TITLE
0.10.0 SketchesReadOnlyException

### ISSUE THREAD

**Issue by hpx7** [DataSketches/sketches-core#156]
Seeing the following after upgrading to 0.10.0:

```
com.yahoo.sketches.SketchesReadOnlyException: Write operation attempted on a read-only class.
	at com.yahoo.sketches.theta.DirectQuickSelectSketchR.hashUpdate(DirectQuickSelectSketchR.java:288)
	at com.yahoo.sketches.theta.UnionImpl.update(UnionImpl.java:261)
```

Didn't see anything helpful in the `Union#update(Sketch sketchIn)` javadocs regarding what might be going wrong.

**Comment by AlexanderSaydakov** [comment]
Could you give more context please? We need to understand what you are doing to reproduce it. If you could reproduce it in a few lines of code, that would be ideal.

**Comment by hpx7** [comment]
I was doing the following:
```
        Union union1 = new SetOperationBuilder().buildUnion();
        union1.update("foo");
        union1 = Sketches.wrapUnion(Memory.wrap(union1.toByteArray()));

        Union union2 = new SetOperationBuilder().buildUnion();
        union2.update("bar");
        union2 = Sketches.wrapUnion(Memory.wrap(union2.toByteArray()));

        union1.update(union2.getResult());
```

Changing it to use `WritableMemory#wrap` instead fixes it for me, so I'll go ahead and close this.

**Comment by AlexanderSaydakov** [comment]
This is exactly how the new memory is supposed to work. You used a read-only wrap, and then tried to update, so it threw a read-only exception, as intended. I know this will take some getting used to.
