### ISSUE TITLE
Duplicate detection

### ISSUE THREAD

**Issue by hpx7** [DataSketches/sketches-core#160]
Hey folks,

Was wondering if you had any thoughts on approximate duplicate detection algorithms. One could conceivably use an HLL (compare cardinality to total stream length), but I don't think the confidence interval there will be satisfyingly tight.

Found this paper which seems potentially interesting: http://www.vldb.org/pvldb/vol6/p589-dutta.pdf

In general, have you had any requests for supporting approximate membership queries?

EDIT: let me know if this isn't the proper channel for discussions like these

**Comment by jmalkin** [comment]
I'll answer the trivial one: This is a reasonable forum for these discussions. We also have a Google Group, but either place is ok.

**Comment by jmalkin** [comment]
From a brief look at the paper, we're not yet sure if it's sublinear and fully mergeable, both of which are requirements for sketches in the library.

Can you explain the use case you had in mind? We haven't generally found anyone for such a sketch to solve some critical business problem. We're more used to situations where duplicate records are certainly not unknown and are tolerated.

**Comment by hpx7** [comment]
Use case: determine whether a particular column is (probably) a primary key

**Comment by AlexanderSaydakov** [comment]
> Use case: determine whether a particular column is (probably) a primary key

How would one use that in practice? Are you reverse engineering a database?

Is removing duplicates your goal? Or detecting the fact that there are duplicates?

> One could conceivably use an HLL (compare cardinality to total stream length), but I don't think the confidence interval there will be satisfyingly tight.

This makes me think that you want to detect if there are duplicates (without determining which ones specifically). What confidence interval would be satisfyingly tight?

**Comment by hpx7** [comment]
Correct, my immediate use is detecting whether there are duplicates at all. This can be useful for when your data is stored in such a way that doesn't enforce uniqueness at write time, but you want to verify that a column is unique after the fact (and don't want to perform an expensive sort).

> What confidence interval would be satisfyingly tight?
As high as possible. An HLL doesn't seem particularly optimized for this use case (estimating cardinality in general is probably a harder problem than estimating the presence of any duplicates at all), and was just wondering if there might be algorithms better suited for this.

**Comment by AlexanderSaydakov** [comment]
> As high as possible

I am afraid this is not an answer. Suppose some sort of a test is "positive" if there are more than 1% duplicates with 95% confidence. Is this tight enough?

**Comment by hpx7** [comment]
How about: there are exactly 0 duplicates with 95% confidence.

Not sure whether that would be possible to determine in O(1) space.

**Comment by jmalkin** [comment]
That's not quite how confidence intervals work for these algorithms, so I'd say it's not possible in O(1) space.

With basically any of these algos, we can return a best estimate and an error range. The confidence interval reflects how likely the true value is to be between the upper and lower bounds of that range. If you want a higher confidence level, it comes at the cost of a wider upper/lower bound range.

**Comment by AlexanderSaydakov** [comment]
If there is any hope of solving this in a sub-linear space, you need to tolerate some error. If you want "exactly 0", then I would think there is no approximate algorithm, which can do this.

**Comment by jmalkin** [comment]
Bloom filters also grow linearly with your data to maintain a stable error rate. If your filter is too small, your false positive rate will start to skyrocket at some point as the number of items grows.
