### ISSUE TITLE
Result list of FrequentItems sketch empty after a while

### ISSUE THREAD

**Issue by tlindener** [DataSketches/sketches-core#199]
I'm currently running the FrequentItem Sketch on the ratings only dataset:
http://jmcauley.ucsd.edu/data/amazon/links.html
I'm creating the sketch and update it with the ASIN (Product ID) from the dataset. In the beginning it works but after a while the result simply gets empty.
```
TopNQueryResult{resultList=[TopNQueryResultItem{item=0007444117, estimate=1180, lowerBound=753, upperBound=1180}, TopNQueryResultItem{item=0007442920, estimate=975, lowerBound=548, upperBound=975}, TopNQueryResultItem{item=0007386648, estimate=872, lowerBound=445, upperBound=872}]}
TopNQueryResult{resultList=[TopNQueryResultItem{item=0007444117, estimate=1180, lowerBound=724, upperBound=1180}, TopNQueryResultItem{item=0007442920, estimate=975, lowerBound=519, upperBound=975}]}
TopNQueryResult{resultList=[TopNQueryResultItem{item=0007444117, estimate=1180, lowerBound=677, upperBound=1180}]}
TopNQueryResult{resultList=[TopNQueryResultItem{item=0007444117, estimate=1180, lowerBound=641, upperBound=1180}]}
TopNQueryResult{resultList=[TopNQueryResultItem{item=0007444117, estimate=1180, lowerBound=603, upperBound=1180}]}
TopNQueryResult{resultList=[]}
```
The TopNQueryResult is just a wrapper for reboxing the results.
SketchMapSize is 64 and error type is ErrorType.NO_FALSE_POSITIVES. I assume this is due to the error type?

**Comment by jmalkin** [comment]
I believe you're running into the distinction between frequent items and top N. If the stream is large enough and distribution of items too flat, then basically nothing will rise above the sketch's noise floor -- and that's possible using either error mode. In those cases, the sketch will return nothing. In effect, the sketch is saying nothing is particularly frequent vs the overall stream. Using a larger sketch may help, but whether it will in this particular case depends on the specific distribution of items. 

You can read a bit more about this in the Returned Results section of the documentation:
https://datasketches.github.io/docs/FrequentItems/FrequentItemsOverview.html

**Comment by tlindener** [comment]
Ah indeed I misunderstood the idea behind the Sketch. Thanks for the explanations!
