### ISSUE TITLE
Naming Conventions ItemSketch

### ISSUE THREAD

**Issue by jleach4** [DataSketches/sketches-core#84]
Small nit.  Since we (Splice Machine) are using both frequencies and quantiles, it would be nice if they were not named the same (ItemSketch)...

**Comment by leerho** [comment]
Yes, I agree this can be a PITA if you are working with both in the same class.  Too bad Java doesn't have TypeDef or similar aliasing. 

The other side of this coin is that our class names were already getting very long and it seemed redundant to keep qualifying a class name with the name of the package that is already imported.

To change this would require a major change to the API (sigh).  But I'd like to hear from others whether this is something that needs to be addressed.

BTW, the Java library has this same problem.
