### ISSUE TITLE
Counting Nulls

### ISSUE THREAD

**Issue by jleach4** [DataSketches/sketches-core#85]
I am currently using Theta, Quantile, and Frequent Sketches to plugin to a RDBMS statistics structure.  It was not clear to me if there is an existing place to count nulls or is that something I should implement separately.

**Comment by AlexanderSaydakov** [comment]
All sketches ignore nulls if the input can be null at all.
What do you mean by counting nulls? In case of counting unique values with Theta sketch, discarding nulls can lead to only one count difference. Hardly a problem at all. In case of estimating the distribution of values with Frequent Items sketch or Quantiles sketch, the easiest way to include null would be to substitute it with a special value appropriate for the domain in question. Say, for use with ItemsSketch<String> it can be 'null' or "NULL" or something like that.

**Comment by jleach4** [comment]
Sounds good.  Still feeling my way around the API and wanted to make sure I am not missing something.
