### ISSUE TITLE
Quantiles Sketch Density

### ISSUE THREAD

**Issue by jleach4** [DataSketches/sketches-core#91]
If you have a quantiles sketch for a bounded set of data, how would you provide an estimate for data out of those bounds?

For example, 

Known values:

int[] values = new int[]{1,2,3,4,5,6,7,8,9,10};

Estimate Between
[12,15]

Can I get the average density from the known values and then apply that to the unknown values?

Thanks
John

**Comment by leerho** [comment]
Without prior knowledge of the actual distribution of the input data you can't make any such assumptions.  And if you have such prior knowledge, you probably don't need the quantiles sketch!  

The purpose of the quantiles sketch is to extract information about an **unknown** distribution of a stream of comparable values.  The PMF of your given function is a rectangle that is zero for values less than 1 and greater than 10, and a height of 1/10 at each of the values in between.  From what the sketch knows, the probability of 12, 15, 1000, or -1000000 are all zero.  

If you, as analyst, wants to make the assumption that the actual distribution is flat for all integers, and there will be no duplicates, that is up to you.  But I would not make that assumption.  

Two examples from the web site:

- On the [Quantiles Accuracy](http://datasketches.github.io/docs/Quantiles/QuantilesAccuracy.html) page, [first figure](http://datasketches.github.io/docs/img/QuantilesCDF.png), I am measuring the accuracy of a very small (k=32) sketch by feeding it a **known** distribution, i.e., the cumulative Standard Normal Distribution.  Even though the sketch never saw values of less than -3 or greater than +3, I know from the mathematics of the Standard Normal Distribution what the probability is of those values occurring.  

- However, on the [Quantiles Overview](http://datasketches.github.io/docs/Quantiles/QuantilesOverview.html) page I am extracting information about the distribution of a stream that I knew nothing about.  The [first figure](http://datasketches.github.io/docs/img/TimeSpentQuantiles.png) gives me clues about the min and max values observed and that the values range over almost 7 orders-of-magnitude.

With this information I query the same sketch again, using the PMF function and a mathematically generated, exponential series of split-points. This yielded the [Histogram](http://datasketches.github.io/docs/img/TimeSpentHistogram.png).

Now, as an analyst, I looked at that shape and recognized that it resembles a lognormal distribution, so I took the liberty to try to fit a mathematically generated lognormal distribution to the observed data, and that is what you see as the red bars in the [Lognormal Model](http://datasketches.github.io/docs/img/TimeSpentLognormal.png).  It works pretty well for values greater than 100 mS and less than 100K mS.  Outside of that, however, the model is pretty shaky!

I hope this helps.
