### ISSUE TITLE
Range Selectivity

### ISSUE THREAD

**Issue by jleach4** [DataSketches/sketches-core#92]
My reading of the quantiles sketch api is that it includes the values provided as the bounds.

int[] foo = new int[] {1,2,3,4,5,6,7,8,9,10};

so the getCDF can handle easily [2,5].

Is there a clear way to handle (2,5)?
 
Would I need to increment in the outer code (transform  (2,5) to [3,4]?

**Comment by leerho** [comment]
I'm not sure I understand your question.  I assume foo is your input stream.  The quantiles sketch automatically tracks the min and max of the values it sees.  So any CDF containing split-points inclusively between the min and max are fair game.  So yes, a getCDF({2,5}) should result in the values {0.1, 0.4, 1.0}.  This is saying that 10% of the values are less than 2, 40% of the values are less than 5, and 100% of the values are less than or equal to the max value.

**Comment by leerho** [comment]
Sorry, I misunderstood (I didn't notice the bracket types :(.  The ranges are always [2, 5). Inclusive on the bottom, and exclusive on the top.   

Remember that these are estimates on ranges of the real number line approximated by double values.  Using double values the difference between [2.0, 5.0] and (2.0, 5.0) should be minor.

However, if what you need is a true "integer" quantiles sketch you could extend the generic version: ItemsSketch<Long>, and then "tweak" the end points by adding or subtracting one.
